/*
		CITD_DQ_UPLOAD_DOMAIN_MAPPING.sql
*/
-- delete from S2_DQ.CITD_DQ_MAPPING

insert	into	S2_DQ.CITD_DQ_MAPPING
		(
		DQ_BU
,		DQ_SCHEMA
,		DQ_SOURCE_TABLE
,		DQ_SOURCE_COLUMN
,		DQ_DOMAIN
		)
select	'HR'
,		'S2_HR'
,		ENTITY_NAME
,		ATTRIBUTE_NAME
,		DOMAIN_NAME
from	CITD_D1_DEV.S2_DQ.DQ_UPLOAD_DQ_DOMAIN_MAPPING
where   DOMAIN_NAME is not null