/*

		CITD_DQ_Load_Domain_Files.sql
		
		created:	20230815	Andy Rupp
		updated:	20231129	Andy Rupp
		
		adopted to S2_DQ - DOMAIN Management

*/

snowsql -a CSVupload1 -d CITD_D1_DEV -s S2_DQ -r ACCOUNTADMIN -w COMPUTE_WH -h rxptimr-kinaxis.snowflakecomputing.com

CREATE OR REPLACE STAGE CITD_D1_DEV.S2_DQ.CITD_DQ ;

CREATE OR REPLACE FILE FORMAT FILE_FORMAT_CSV
TYPE = CSV
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'NULL')
EMPTY_FIELD_AS_NULL = TRUE
COMPRESSION = GZIP
;

PUT 'file://c:/kinaxis_work/Project Development by BU/HR Human Resources/HR_PoC_Employee_20/DQ_2024/DQ_UPLOAD_DQ_DOMAIN.csv' @CITD_D1_DEV.S2_DQ.CITD_DQ ;
PUT 'file://c:/kinaxis_work/Project Development by BU/HR Human Resources/HR_PoC_Employee_20/DQ_2024/DQ_UPLOAD_DQ_DOMAIN_MAPPING.csv' @CITD_D1_DEV.S2_DQ.CITD_DQ ;

delete from DQ_UPLOAD_DQ_DOMAIN ;
delete from DQ_UPLOAD_DQ_DOMAIN_MAPPING ;

COPY INTO CITD_D1_DEV.S2_DQ.DQ_UPLOAD_DQ_DOMAIN
FROM @CITD_DQ
FILES = ('DQ_UPLOAD_DQ_DOMAIN.csv.gz')
FILE_FORMAT = (FORMAT_NAME = 'FILE_FORMAT_CSV' , ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
;
COPY INTO CITD_D1_DEV.S2_DQ.DQ_UPLOAD_DQ_DOMAIN_MAPPING
FROM @CITD_DQ
FILES = ('DQ_UPLOAD_DQ_DOMAIN_MAPPING.csv.gz')
FILE_FORMAT = (FORMAT_NAME = 'FILE_FORMAT_CSV' , ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
;