/*
	HR_EMP_ETL_EMP_Job_Code.sql
	
	created:	20240308	Andy Rupp
	updated:
	
	This is a TEST release.
	populate the table HR_EMP_JOB_CODE.
	
*/

TRUNCATE	TABLE	CITD_D1_DEV.S2_HR.HR_EMP_JOB_CODE
;

insert	into	CITD_D1_DEV.S2_HR.HR_EMP_JOB_CODE
		(
		JOB_CODE
,		JOB_CODE_TITLE
,		JOB_GRADE
,		JOB_FUNCTION
,		JOB_LEVEL
,		JOB_LEVEL_DESCRIPTION
,		BONUS_PLAN_TYPE
,		JOB_NAME
,		JOB_NAME_DEFAULT
,		JOB_NAME_US
,		STANDARD_HOURS
,		DT_CRE_AT
,		DT_CRE_BY
,		DT_UPD_AT
,		DT_UPD_BY
,		DT_VALID_FROM
,		DT_VALID_TO
,		ACTIVE
		)
select	JC.EXTERNALCODE
,		nvl(JC.CUST_DEFAULTJOBCODETITLE,'NA')
,		nvl(JC.GRADE,'NA')
,		nvl(JC.JOBFUNCTION,'NA')
,		nvl(JC.JOBLEVEL,'NA')
,		'JOB_LEVEL_DESC'
,		nvl(JC.CUST_TYPEOFBONUSPLAN,'NA')
,		JC.NAME
,		JC.NAME_DEFAULTVALUE
,		JC.NAME_EN_US
,		JC.STANDARDHOURS
,		JC.CREATEDON		-- DT_CRE_AT
,		JC.CREATEDBY		-- DT_CRE_BY
,		JC.LASTMODIFIEDON	-- DT_UPD_AT
,		JC.LASTMODIFIEDBY	-- DT_UPD_BY
,		JC.STARTDATE		-- DT_VALID_FROM
,		CASE JC.ENDDATE
		WHEN '9999-12-31 00:00:00.000'	then	NULL
								ELSE			JC.ENDDATE
		END CASE			-- DT_VALID_TO
,		JC.STATUS			-- ACTIVE
from	CORPITDATAPROD.EDW_LND_TB.SAPSF_FO_JOBCODE	JC
;
UPDATE	CITD_D1_DEV.S2_HR.HR_EMP_JOB_CODE
SET		ACTIVE			= '1'
where	ACTIVE			= 'A'
;
UPDATE	CITD_D1_DEV.S2_HR.HR_EMP_JOB_CODE
SET		ACTIVE			= '0'
where	ACTIVE			= 'I'
;