/*
	HR_EMP_ETL_EMP_DIV.sql
	
	created:	20240310	Andy Rupp
	updated:
	
	This is a TEST release.
	populate the table HR_FO_DIVISION.
	
*/

TRUNCATE	TABLE	CITD_D1_DEV.S2_HR.HR_FO_DIVISION
;
INSERT	INTO	CITD_D1_DEV.S2_HR.HR_FO_DIVISION
		(
		BU_CD
,		DEPT_CD
,		DIV_CD
,		ABBR_DIV
,		NAME_DIV
,		DT_CRE_AT
,		DT_CRE_BY
,		DT_UPD_AT
,		DT_UPD_BY
,		DT_VALID_FROM
,		DT_VALID_TO
,		ACTIVE
		)
select	DISTINCT
		DIV.BU_ID
,		DPT.DPT_ID
,		DIV.DIV_ID
,		DIV.NAME_SHORT
,		DIV.DIV_NAME
,		'2000-01-01'
,		NULL
,		'2000-01-01'
,		NULL
,		'2000-01-01'
,		'2099-12-31'
,		DIV.ACTIVE
from	CITD_D1_DEV.S2_REF.ORG_DIV		DIV
LEFT OUTER JOIN
		CITD_D1_DEV.S2_REF.ORG_DPT		DPT
	ON	DIV.BU_ID			= DPT.BU_ID
	AND	DIV.CMPY_ID			= DPT.CMPY_ID
;