/*
	HR_EMP_ETL_EMP_Personal.sql
	
	created:	20240310	Andy Rupp
	updated:
	
	This is a TEST release.
	populate the table HR_EMP_PERSONAL.
	
*/

TRUNCATE	TABLE	S2_HR.HR_EMP_PERSONAL
;

insert	into	CITD_D1_DEV.S2_HR.HR_EMP_PERSONAL
		(
		EMPLOYEE_ID ,
		COUNTRY_ISO3166_2_CHAR3,
		LANGUAGE,
		NAME_FIRST,
		NAME_FAMILY
		NAME_MI,
		NAME_FIRST_PREFERRED,
		NAME_FAMILY_PREFERRED,
		GENDER_CODE,
		SALUTATION,
		HONORIFICATION,
		DT_CRE_AT TIMESTAMP_NTZ(9,
		DT_CRE_BY,
		DT_UPD_AT,
		DT_UPD_BY,
		DT_VALID_FROM ,
		DT_VALID_TO ,
		ACTIVE
		)
select

		FIRSTNAME
		LASTNAME
		PERSONIDEXTERNAL
		PREFERREDNAME
		STARTDATE
		GENDER

from	CORPITDATAPROD.EDW_LND_TB.SAPSF_PER_PERSONAL
;