/*
	HR_EMP_ETL_EMP_ADDR_PERSONAL.sql
	
	created:	20240310	Andy Rupp
	updated:
	
	This is a TEST release.
	populate the table HR_EMP_ADDR_PERSONAL.
	
*/

TRUNCATE	TABLE	S2_HR.HR_EMP_ADDR_PERSONAL
;
insert	into	CITD_D1_DEV.S2_HR.HR_EMP_ADDR_PERSONAL
		(
		EMPLOYEE_ID
,		COUNTRY_ISO3166_2_CHAR3
,		DT_CRE_AT
,		DT_CRE_BY
,		DT_UPD_AT
,		DT_UPD_BY
,		DT_VALID_FROM
,		DT_VALID_TO
,		ACTIVE
		)
select	PERSONIDEXTERNAL
,		COUNTRY
,		'2000-01-01'
,		NULL
,		LASTMODIFIEDDATETIME
,		NULL
,		STARTDATE
,		ENDDATE
,		'1'
FROM	CORPITDATAPROD.EDW_LND_TB.SAPSF_PER_ADDRESS
;