/*
	HR_EMP_ETL_HR_EMP_ADDR_WORK.sql
	
	created:	20240310	Andy Rupp
	updated:
	
	This is a TEST release.
	populate the table HR_EMP_ADDR_WORK.
	
*/

TRUNCATE	TABLE	S2_HR.HR_EMP_ADDR_WORK
;
insert	into	CITD_D1_DEV.S2_HR.HR_EMP_ADDR_WORK
		(
		EMPLOYEE_ID
,		COUNTRY_ISO3166_2_CHAR3
,		DT_CRE_AT
,		DT_CRE_BY
,		DT_UPD_AT
,		DT_UPD_BY
,		DT_VALID_FROM
,		DT_VALID_TO
,		ACTIVE
		)
SELECT	DISTINCT
		EMPLOYEE_ID
,		nvl(WORK_COUNTRY_CD,'XXX')
,		'2000-01-01'
,		NULL
,		'2000-01-01'
,		NULL
,		'2000-01-01'
,		'2099-12-31'
,		'1'
FROM	CORPITDATAPROD.EDW_INT_TB.EMPLOYEE_JOB
GROUP	BY
		EMPLOYEE_ID
,		WORK_COUNTRY_CD
;