/*
	HR_EMP_ETL_FACTS_HEADCOUNT.sql
	
	created:	20240310	Andy Rupp
	updated:
	
	This is a TEST release.
	populate the table HR_FCT_HEADCOUNT.
	
*/

TRUNCATE	TABLE	S2_HR.HR_FCT_HEADCOUNT
;

insert	into	S2_HR.HR_FCT_HEADCOUNT
		(
		COUNTRY_ISO3166_2_CHAR3
,		CMPY_CD
,		BU_CD
,		DEPT_CD
,		EMPLOYEE_ID
,		EMP_STATUS
,		EVENT_CD
,		EVENT_REASON_CD
,		EMP_TYPE_CD
,		EMP_CLASS_CD
,		JOB_CODE
,		JOB_CODE_TITLE
,		JOB_GRADE
,		JOB_LEVEL
,		ACTIVE
,		DATE_STARTED
,		DATE_ENDED
,		DURATION_IN_MONTHS
,		VOLUME_HC
		)
select	distinct
		ADW.COUNTRY_ISO3166_2_CHAR3				-- COUNTRY_ISO3166_2_CHAR3
,		JOB.CMPY_CD								-- CMPY_CD
,		JOB.BU_CD								-- BU_CD
,		JOB.DEPT_CD								-- DEPT_CD
,		nvl(EPL.EMPLOYEE_ID,'999999')			-- EMPLOYEE_ID
,		nvl(JOB.EMP_STATUS,'N/A')				-- EMP_STATUS
,		nvl(JOB.EVENT_CD,'N/A')					-- EVENT_CD
,		nvl(JOB.EVENT_REASON_CD,'N/A')			-- EVENT_REASON_CD
,		nvl(EPL.EMP_TYPE_CD,'N/A')				-- EMP_TYPE_CD
,		nvl(JOB.EMP_CLASS_CD,'N/A')				-- EMP_CLASS_CD
,		nvl(JOB.JOB_CODE,'N/A')					-- JOB_CODE
,		nvl(JOB.JOB_CODE_TITLE,'N/A')			-- JOB_CODE_TITLE
,		nvl(JOB.JOB_GRADE,'N/A')				-- JOB_GRADE
,		nvl(JOB.JOB_LEVEL,'N/A')				-- JOB_LEVEL
,		EPL.ACTIVE
,		nvl(EPL.START_DATE,'2000-01-01')		-- DATE_STARTED
,		nvl(EPL.LAST_DATE_WORKED,CURRENT_DATE)	-- DATE_ENDED
,		TRUNC((NVL(EPL.LAST_DATE_WORKED,CURRENT_DATE)
	-	EPL.START_DATE) / 30 ,0)				--DURATION_IN_MONTHS
,		count(distinct EPL.EMPLOYEE_ID)			-- VOLUME_HC
-- ,		max(EPL.DT_VALID_FROM)					-- get ONE record back
from	S2_HR.HR_EMP_EMPLOYMENT			EPL
JOIN	S2_HR.HR_EMP_JOB				JOB
	ON	EPL.EMPLOYEE_ID					= JOB.EMPLOYEE_ID
JOIN	S2_HR.HR_EMP_ADDR_WORK			ADW
	ON	EPL.EMPLOYEE_ID					= ADW.EMPLOYEE_ID
-- JOIN	S2_HR.HR_FO_DEPARTMENT			DPT
-- 	ON	JOB.DEPT_CD						= DPT.DEPT_CD
-- 	AND	JOB.BU_CD						= DPT.BU_CD
-- JOIN	S2_HR.HR_FO_BUSINESS_UNIT		BU
-- 	ON	DPT.BU_CD						= BU.BU_CD
-- JOIN	S2_HR.HR_FO_COMPANY				CMPY
--	ON	BU.CMPY_CD						= CMPY.CMPY_CD
where   (
		EPL.LAST_DATE_WORKED            IS NULL
	AND	EPL.DT_VALID_TO					IS NULL
		)
GROUP	BY
		ADW.COUNTRY_ISO3166_2_CHAR3
,		JOB.CMPY_CD				
,		JOB.BU_CD					
,		JOB.DEPT_CD					
,		EPL.EMPLOYEE_ID				
,		JOB.EMP_STATUS				
,		JOB.EVENT_CD				
,		JOB.EVENT_REASON_CD			
,		EPL.EMP_TYPE_CD				
,		JOB.EMP_CLASS_CD			
,		JOB.JOB_CODE				
,		JOB.JOB_CODE_TITLE			
,		JOB.JOB_GRADE				
,		JOB.JOB_LEVEL
,		EPL.ACTIVE				
,		EPL.START_DATE				
,		EPL.LAST_DATE_WORKED
ORDER	by
		5,1,2,3
;