/*
	HR_EMP_ETL_EMP_Country.sql
	
	created:	20240310	Andy Rupp
	updated:
	
	This is a TEST release.
	populate the table HR_FO_COUNTRY.
	
*/

TRUNCATE	TABLE	CITD_D1_DEV.S2_HR.HR_FO_COUNTRY
;

INSERT	INTO	CITD_D1_DEV.S2_HR.HR_FO_COUNTRY
		(
		COUNTRY_ISO3166_2_CHAR3
,		COUNTRY_ISO3166_2_CHAR2
,		COUNTRY_ISO3166_2_NUM
,		COUNTRY_NAME
,		COUNTRY_ISO4217_CURRENCY
,		TERRITORY_ID
,		DT_CRE_AT
,		DT_CRE_BY
,		DT_UPD_AT
,		DT_UPD_BY
,		DT_VALID_FROM
,		DT_VALID_TO
,		ACTIVE
		)
SELECT	FOC.WORK_COUNTRY_CD
,		REC.COUNTRY_ISO_3166_ALPHA_2	-- added
,		FOC.WORK_COUNTRY_CD_NUM
,		FOC.WORK_COUNTRY_DESC
,		FOC.CURRENCY
,		FOC.TERRITORY_ID
,		FOC.CREATED_DTM
,		NULL
,		FOC.LAST_MODIFIED_DTM
,		NULL
,		FOC.EFFECTIVE_START_DTM
,		FOC.EFFECTIVE_END_DTM
,		FOC.STATUS
FROM	CITD_D1_DEV.S2_HR.SOURCE_FAKE_HR_EMP_FO_COUNTRY		FOC
LEFT OUTER JOIN
		CITD_D1_DEV.S2_REF.REF_COUNTRY						REC
	ON	FOC.WORK_COUNTRY_CD		= REC.COUNTRY_ISO_3166_ALPHA_3
;
UPDATE	CITD_D1_DEV.S2_HR.HR_FO_COUNTRY
SET		ACTIVE			= '1'
where	ACTIVE			= 'A'
;
UPDATE	CITD_D1_DEV.S2_HR.HR_FO_COUNTRY
SET		ACTIVE			= '0'
where	ACTIVE			<> 'A'
;
UPDATE	CITD_D1_DEV.S2_HR.HR_FO_COUNTRY
SET		ACTIVE			= '0'
where	DT_VALID_TO		IS NOT NULL
;
UPDATE	CITD_D1_DEV.S2_HR.HR_FO_COUNTRY
SET		ACTIVE			= '1'
where	DT_VALID_TO		IS NULL
;