/*
	HR_EMP_ETL_EMP_Status.sql
	
	created:	20240308	Andy Rupp
	updated:
	
	This is a TEST release.
	populate the table HR_EMP_STATUS.
	
*/

TRUNCATE	TABLE	CITD_D1_DEV.S2_HR.HR_EMP_STATUS
;

insert	into	CITD_D1_DEV.S2_HR.HR_EMP_STATUS
		(
		EMP_STATUS
,		STATUS_DESCRIPTION
,		DT_CRE_AT
,		DT_CRE_BY
,		DT_UPD_AT
,		DT_UPD_BY
,		DT_VALID_FROM
,		DT_VALID_TO
,		ACTIVE
		)
select	EMP_STATUS_CD
,		EMP_STATUS_DESC
,		NULL				-- DT_CRE_AT
,		NULL				-- DT_CRE_BY
,		LAST_REFRESH_DTM	-- DT_UPD_AT
,		NULL				-- DT_UPD_BY
,		NULL				-- DT_VALID_FROM
,		NULL				-- DT_VALID_TO
,		STATUS				-- ACTIVE
from	CITD_D1_DEV.S2_HR.SOURCE_FAKE_HR_EMP_STATUS
;
UPDATE	CITD_D1_DEV.S2_HR.HR_EMP_STATUS
SET		ACTIVE			= '0'
where	ACTIVE			= 'I'
;
UPDATE	CITD_D1_DEV.S2_HR.HR_EMP_STATUS
SET		ACTIVE			= '1'
where	ACTIVE			= 'A'
;