/*
	HR_EMP_ETL_EMP_Employment.sql
	
	created:	20240308	Andy Rupp
	updated:
	
	This is a TEST release.
	populate the table HR_EMP_EMPLOYMENT.
	
*/

TRUNCATE	TABLE	CITD_D1_DEV.S2_HR.HR_EMP_EMPLOYMENT
;

insert	into	CITD_D1_DEV.S2_HR.HR_EMP_EMPLOYMENT
		(
		EMPLOYEE_ID
,		USER_ID
,		EMP_TYPE_CD
,		LAST_DATE_WORKED
,		ORIGINAL_START_DATE
,		SALARY_END_DATE
,		PAYROLL_END_DATE
,		SERVICE_DATE
,		START_DATE
,		STOCK_END_DATE
,		HIRING_NOT_COMPLETED
,		IS_CONTINGENT_WORKER
,		IS_EC_RECORD
,		REGRET_TERMINATION
,		DT_CRE_AT
,		DT_CRE_BY
,		DT_UPD_AT
,		DT_UPD_BY
,		DT_VALID_FROM
,		DT_VALID_TO
,		ACTIVE
		)
select	PERSONIDEXTERNAL
,		USERID
,		NULL					-- EMP_TYPE_CD
,		LASTDATEWORKED
,		ORIGINALSTARTDATE
,		SALARYENDDATE
,		PAYROLLENDDATE
,		SERVICEDATE
,		STARTDATE
,		STOCKENDDATE
,		CASE	HIRINGNOTCOMPLETED
		WHEN TRUE	then '1'
		WHEN FALSE then '0'
		END CASE
,		CASE	ISCONTINGENTWORKER
		WHEN TRUE	then '1'
		WHEN FALSE then '0'
		END CASE
,		CASE	ISECRECORD
		WHEN TRUE	then '1'
		WHEN FALSE then '0'
		END CASE
,		CASE	REGRETTERMINATION
		WHEN TRUE	then '1'
		WHEN FALSE then '0'
		END CASE
,		CREATEDDATETIME
,		NULL
,		LASTMODIFIEDDATETIME
,		NULL
,		STARTDATE
,		CASE ENDDATE
		WHEN '9999-12-31 00:00:00.000'	then	NULL
										ELSE	ENDDATE
		END CASE			-- DT_VALID_TO
,		'1'
from	CORPITDATAPROD.EDW_LND_TB.SAPSF_EMP_EMPLOYMENT
;
UPDATE	CITD_D1_DEV.S2_HR.HR_EMP_EMPLOYMENT
SET		ACTIVE			= '0'
where	DT_VALID_TO		IS NOT NULL
;
UPDATE	CITD_D1_DEV.S2_HR.HR_EMP_EMPLOYMENT
SET		ACTIVE			= '1'
where	DT_VALID_TO		IS NULL
;