/*
	HR_EMP_ETL_EMP_Company.sql
	
	created:	20240310	Andy Rupp
	updated:
	
	This is a TEST release.
	populate the table HR_FO_COMPANY.
	
*/

TRUNCATE	TABLE	CITD_D1_DEV.S2_HR.HR_FO_COMPANY
;

INSERT	INTO	CITD_D1_DEV.S2_HR.HR_FO_COMPANY
		(
		CMPY_CD
,		ABBR_COMPANY
,		NAME_COMPANY
,		COUNTRY_ISO3166_2_CHAR3
,		DT_CRE_AT
,		DT_CRE_BY
,		DT_UPD_AT
,		DT_UPD_BY
,		DT_VALID_FROM
,		DT_VALID_TO
,		ACTIVE
		)
select	COMPANY_CD
,		'ABBR'
,		COMPANY_DESC
,		WORK_COUNTRY_CD
,		'2000-01-01'
,		NULL
,		'2000-01-01'
,		NULL
,		'2000-01-01'
,		'2099-12-31'
,		STATUS
from	CITD_D1_DEV.S2_HR.SOURCE_FAKE_HR_EMP_FO_COMPANY
;
UPDATE	CITD_D1_DEV.S2_HR.HR_FO_COMPANY
SET		ACTIVE			= '0'
where	ACTIVE			<> 'A'
;
UPDATE	CITD_D1_DEV.S2_HR.HR_FO_COMPANY
SET		ACTIVE			= '1'
where	ACTIVE			= 'A'
;
