/*
	HR_EMP_ETL_EMP_CC.sql
	
	created:	20240310	Andy Rupp
	updated:
	
	This is a TEST release.
	populate the table HR_FO_COST_CENTER.
	
*/

TRUNCATE	TABLE	CITD_D1_DEV.S2_HR.HR_FO_COST_CENTER
;
INSERT	INTO	CITD_D1_DEV.S2_HR.HR_FO_COST_CENTER
		(
		COST_CENTER
,		COST_CENTER_NAME
,		DT_CRE_AT
,		DT_CRE_BY
,		DT_UPD_AT
,		DT_UPD_BY
,		DT_VALID_FROM
,		DT_VALID_TO
,		ACTIVE
		)
select	COST_CENTER_CD
,		COST_CENTER_DESC
,		'2000-01-01'
,		NULL
,		'2000-01-01'
,		NULL
,		'2000-01-01'
,		'2099-12-31'
,		STATUS
from	CITD_D1_DEV.S2_HR.SOURCE_FAKE_HR_EMP_FO_COST_CENTER
;