-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2024-03-20 15:28:57 ADT
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE or REPLACE TABLE HR_EMP 
    (
     employee_id VARCHAR (20) NOT NULL , 
     user_id VARCHAR (40) , 
     name_first VARCHAR (40) , 
     name_family VARCHAR (80) , 
     name_mi VARCHAR (1) , 
     name_first_preferred VARCHAR (40) , 
     name_family_preferred VARCHAR (80) , 
     e_mail VARCHAR (50) , 
     name_account VARCHAR (80) , 
     GENDER_CODE VARCHAR (10) , 
     salutation VARCHAR (5) , 
     Honorification VARCHAR (10) , 
     dt_hired DATE , 
     dt_started DATE , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_ADDR_PERSONAL 
    (
     employee_id VARCHAR (20) NOT NULL , 
     COUNTRY_ISO3166_2_CHAR3 VARCHAR (3) NOT NULL , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_ADDR_PERSONAL_HISTORY 
    (
     employee_id VARCHAR (20) NOT NULL , 
     COUNTRY_ISO3166_2_CHAR3 VARCHAR (3) NOT NULL , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE NOT NULL , 
     dt_valid_to DATE NOT NULL , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_ADDR_WORK 
    (
     employee_id VARCHAR (20) NOT NULL , 
     COUNTRY_ISO3166_2_CHAR3 VARCHAR (3) NOT NULL , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_ADDR_WORK_HISTORY 
    (
     employee_id VARCHAR (20) NOT NULL , 
     COUNTRY_ISO3166_2_CHAR3 VARCHAR (3) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_BANK_ACC_TRANSIT 
    (
     employee_id VARCHAR (20) NOT NULL , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_BANK_INFO 
    (
     employee_id VARCHAR (20) NOT NULL , 
     BANK_NAME VARCHAR (120) , 
     BANK_NAME_ABBR VARCHAR (30) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_BANK_INFO_HISTORY 
    (
     employee_id2 VARCHAR (20) NOT NULL , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE NOT NULL , 
     dt_valid_to DATE NOT NULL , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_CLASS 
    (
     EMP_CLASS_CD VARCHAR (20) NOT NULL , 
     EMP_CLASS_DESC VARCHAR (120) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_EMPLOYMENT 
    (
     employee_id VARCHAR (20) NOT NULL , 
     USER_ID VARCHAR (40) , 
     EMP_TYPE_CD VARCHAR (20) , 
     LAST_DATE_WORKED DATE , 
     ORIGINAL_START_DATE DATE , 
     SALARY_END_DATE DATE , 
     PAYROLL_END_DATE DATE , 
     SERVICE_DATE DATE , 
     START_DATE DATE , 
     STOCK_END_DATE DATE , 
     HIRING_NOT_COMPLETED VARCHAR (3) , 
     IS_CONTINGENT_WORKER VARCHAR (3) , 
     IS_EC_RECORD VARCHAR (3) , 
     REGRET_TERMINATION VARCHAR (3) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_EMPLOYMENT_HISTORY 
    (
     employee_id VARCHAR (20) NOT NULL , 
     USER_ID VARCHAR (40) , 
     EMP_TYPE_CD VARCHAR (20) , 
     LAST_DATE_WORKED DATE , 
     ORIGINAL_START_DATE DATE , 
     SALARY_END_DATE DATE , 
     PAYROLL_END_DATE DATE , 
     SERVICE_DATE DATE , 
     START_DATE DATE , 
     STOCK_END_DATE DATE , 
     HIRING_NOT_COMPLETED VARCHAR (3) , 
     IS_CONTINGENT_WORKER VARCHAR (3) , 
     IS_EC_RECORD VARCHAR (3) , 
     REGRET_TERMINATION VARCHAR (3) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_EVENT 
    (
     EVENT_CD VARCHAR (80) NOT NULL , 
     EVENT_DESC VARCHAR (120) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_EVENT_REASON 
    (
     EVENT_CD VARCHAR (80) NOT NULL , 
     EVENT_REASON_CD VARCHAR (80) NOT NULL , 
     EVENT_REASON_DESC VARCHAR (120) , 
     REASON_STATUS VARCHAR (1) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_GENDER 
    (
     GENDER_CODE VARCHAR (10) NOT NULL , 
     GENDER_DESC VARCHAR (80) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE NOT NULL , 
     dt_valid_to DATE NOT NULL , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_HISTORY 
    (
     employee_id VARCHAR (20) NOT NULL , 
     user_id VARCHAR (40) , 
     name_first VARCHAR (40) , 
     name_family VARCHAR (80) , 
     name_mi VARCHAR (1) , 
     name_first_preferred VARCHAR (40) , 
     name_family_preferred VARCHAR (80) , 
     e_mail VARCHAR (50) , 
     name_account VARCHAR (80) , 
     GENDER_CODE VARCHAR (10) , 
     salutation VARCHAR (5) , 
     Honorification VARCHAR (10) , 
     dt_hired DATE , 
     dt_started DATE , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_JOB 
    (
     employee_id VARCHAR (20) NOT NULL , 
     HOST_MANAGER VARCHAR (20) , 
     CMPY_CD VARCHAR (10) , 
     BU_CD VARCHAR (10) , 
     DEPT_CD VARCHAR (10) , 
     OFFICE_CODE VARCHAR (80) , 
     EMP_CLASS_CD VARCHAR (20) , 
     EMP_STATUS VARCHAR (20) , 
     EVENT_CD VARCHAR (80) , 
     EVENT_REASON_CD VARCHAR (80) , 
     POSITION_CODE VARCHAR (20) , 
     REGULAR_TEMP VARCHAR (5) , 
     IS_FULLTIME_EMPLOYEE VARCHAR (3) , 
     FTE DECIMAL (5,3) , 
     JOB_CODE VARCHAR (20) , 
     JOB_GRADE VARCHAR (20) , 
     JOB_CODE_TITLE VARCHAR (120) , 
     JOB_LEVEL VARCHAR (20) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  , 
     EVENT_REASON_CD1 VARCHAR (80) 
    )
;

CREATE or REPLACE TABLE HR_EMP_JOB_CODE 
    (
     JOB_CODE VARCHAR (20) NOT NULL , 
     JOB_CODE_TITLE VARCHAR (120) NOT NULL , 
     JOB_GRADE VARCHAR (20) NOT NULL , 
     JOB_FUNCTION VARCHAR (20) , 
     JOB_LEVEL VARCHAR (20) NOT NULL , 
     JOB_LEVEL_DESCRIPTION VARCHAR (120) , 
     BONUS_PLAN_TYPE VARCHAR (20) , 
     JOB_NAME VARCHAR (120) , 
     JOB_NAME_DEFAULT VARCHAR (120) , 
     JOB_NAME_US VARCHAR (120) , 
     STANDARD_HOURS VARCHAR (2) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_JOB_HISTORY 
    (
     employee_id VARCHAR (20) NOT NULL , 
     HOST_MANAGER VARCHAR (20) , 
     CMPY_CD VARCHAR (10) , 
     BU_CD VARCHAR (10) , 
     DEPT_CD VARCHAR (10) , 
     OFFICE_CODE VARCHAR (80) , 
     EMP_CLASS_CD VARCHAR (20) , 
     EMP_STATUS VARCHAR (20) , 
     EVENT_CD VARCHAR (80) , 
     EVENT_REASON_CD VARCHAR (80) , 
     POSITION_CODE VARCHAR (20) , 
     REGULAR_TEMP VARCHAR (5) , 
     IS_FULLTIME_EMPLOYEE VARCHAR (3) , 
     FTE DECIMAL (5,3) , 
     JOB_CODE VARCHAR (20) , 
     JOB_GRADE VARCHAR (20) , 
     JOB_CODE_TITLE VARCHAR (120) , 
     JOB_LEVEL VARCHAR (20) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  , 
     EVENT_REASON_CD1 VARCHAR (80) 
    )
;

CREATE or REPLACE TABLE HR_EMP_MGR 
    (
     employee_id VARCHAR (20) NOT NULL , 
     MANAGER_ID VARCHAR (20) NOT NULL , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_MGR_HISTORY 
    (
     employee_id VARCHAR (20) NOT NULL , 
     MANAGER_ID VARCHAR (20) NOT NULL , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_PERSONAL 
    (
     employee_id VARCHAR (20) NOT NULL , 
     COUNTRY_ISO3166_2_CHAR3 VARCHAR (3) , 
     LANGUAGE VARCHAR (2) , 
     name_first VARCHAR (40) , 
     name_family VARCHAR (80) , 
     name_mi VARCHAR (1) , 
     name_first_preferred VARCHAR (40) , 
     name_family_preferred VARCHAR (80) , 
     GENDER_CODE VARCHAR (10) , 
     salutation VARCHAR (5) , 
     Honorification VARCHAR (10) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_PERSONAL_HISTORY 
    (
     employee_id2 VARCHAR (20) NOT NULL , 
     LANGUAGE VARCHAR (2) , 
     name_first VARCHAR (80) , 
     name_family VARCHAR (80) , 
     name_mi VARCHAR (80) , 
     name_first_preferred VARCHAR (80) , 
     name_family_preferred VARCHAR (80) , 
     GENDER_CODE VARCHAR (10) , 
     salutation VARCHAR (5) , 
     Honorification VARCHAR (10) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_POSITION 
    (
     POSITION_CODE VARCHAR (20) NOT NULL , 
     LEGACY_POSITION_ID VARCHAR (20) , 
     REGULAR_TEMPORARY VARCHAR (5) , 
     TARGET_FTE DECIMAL (5,3) , 
     STANDARD_HRS VARCHAR (2) , 
     VACANT_IND VARCHAR (5) , 
     EFFECTIVE_STATUS VARCHAR (1)  , 
     JOB_CODE VARCHAR (20) , 
     JOB_GRADE VARCHAR (20) , 
     JOB_CODE_TITLE VARCHAR (120) , 
     JOB_LEVEL VARCHAR (20) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_STATUS 
    (
     EMP_STATUS VARCHAR (20) NOT NULL , 
     STATUS_DESCRIPTION VARCHAR (120) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_TIME 
    (
     employee_id VARCHAR (20) NOT NULL , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_EMP_TYPE 
    (
     EMP_TYPE_CD VARCHAR (20) NOT NULL , 
     EMP_TYPE_DESC VARCHAR (120) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_FO_BUSINESS_UNIT 
    (
     CMPY_CD VARCHAR (10) NOT NULL , 
     BU_CD VARCHAR (10) NOT NULL , 
     ABBR_BU VARCHAR (20) NOT NULL , 
     NAME_BU VARCHAR (80) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_FO_COMPANY 
    (
     CMPY_CD VARCHAR (10) NOT NULL , 
     ABBR_COMPANY VARCHAR (20) NOT NULL , 
     NAME_COMPANY VARCHAR (80) NOT NULL , 
     COUNTRY_ISO3166_2_CHAR3 VARCHAR (3) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_FO_COST_CENTER 
    (
     COST_CENTER VARCHAR (10) NOT NULL , 
     COST_CENTER_NAME VARCHAR (120) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_FO_COUNTRY 
    (
     COUNTRY_ISO3166_2_CHAR3 VARCHAR (3) NOT NULL , 
     COUNTRY_ISO3166_2_CHAR2 VARCHAR (2) , 
     COUNTRY_ISO3166_2_NUM INTEGER , 
     COUNTRY_NAME VARCHAR (80) , 
     COUNTRY_ISO4217_CURRENCY VARCHAR (3) , 
     TERRITORY_ID VARCHAR (20) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_FO_DEPARTMENT 
    (
     CMPY_CD VARCHAR (10) , 
     BU_CD VARCHAR (10) NOT NULL , 
     DEPT_CD VARCHAR (10) NOT NULL , 
     ABBR_DEPT VARCHAR (20) NOT NULL , 
     NAME_DEPT VARCHAR (80) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_FO_DIVISION 
    (
     BU_CD VARCHAR (10) NOT NULL , 
     DEPT_CD VARCHAR (10) , 
     DIV_CD VARCHAR (10) NOT NULL , 
     ABBR_DIV VARCHAR (20) NOT NULL , 
     NAME_DIV VARCHAR (80) , 
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_HOLIDAY_ASSIGNMENT 
    (
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_HOLIDAY_CALENDAR 
    (
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_HOLIDAYS 
    (
     dt_cre_at DATETIME , 
     dt_cre_by VARCHAR (20) , 
     dt_upd_at DATETIME , 
     dt_upd_by VARCHAR (20) , 
     dt_valid_from DATE , 
     dt_valid_to DATE , 
     active VARCHAR (1)  
    )
;

CREATE or REPLACE TABLE HR_OFFICE_LOCATION 
    (
     OFFICE_CODE VARCHAR (80) NOT NULL , 
     OFFICE_NAME VARCHAR (80) , 
     OFFICE_DESCRIPTION VARCHAR (120) 
    )
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE or REPLACE TABLE                            36
-- CREATE INDEX                             0
-- ALTER TABLE                              0
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
