/*
	HR_EMP_ETL_FACTS_HEADCOUNT_View.sql
	
	created:	20240311	Andy Rupp
	updated:
	
	This is a TEST release.
	populate the table HR_FCT_HEADCOUNT.
	
*/

Create or Replace VIEW	S2_HR.HR_FCT_HEADCOUNT_V
as
select	ADP.COUNTRY_ISO3166_2_CHAR3
,		JOB.CMPY_CD
,		CMPY.CMPY_NAME
,		JOB.BU_CD
,		BU.BU_NAME
,		JOB.DEPT_CD
,		DPT.DPT_NAME
,		EPL.EMPLOYEE_ID
,		JOB.EMP_STATUS
,		EST.STATUS_DESCRIPTION
,		JOB.EVENT_CD
,		JOB.EVENT_REASON_CD
,		EVR.EVENT_REASON_DESC
,		EPL.EMP_TYPE_CD
,		ETY.EMP_TYPE_DESC
,		JOB.EMP_CLASS_CD
,		ECL.EMP_CLASS_DESC
,		JOB.JOB_CODE
,		JOB.JOB_CODE_TITLE
,		JOB.JOB_GRADE
,		JOB.JOB_LEVEL
,		EPL.ACTIVE
,		JOB.DT_VALID_FROM
,		JOB.DT_VALID_TO
,		TRUNC((NVL(EPL.LAST_DATE_WORKED,CURRENT_DATE)
	-	EPL.START_DATE) / 30 ,0)				--DURATION_IN_MONTHS
,		count(distinct EPL.EMPLOYEE_ID)			-- VOLUME_HC
,		max(EPL.START_DATE)						-- get ONE record back
-- from	S2_HR.HR_FCT_HEADCOUNT			FCT
from	S2_HR.HR_EMP_EMPLOYMENT			EPL
JOIN	S2_HR.HR_EMP_JOB				JOB
	ON	EPL.EMPLOYEE_ID					= JOB.EMPLOYEE_ID
LEFT OUTER JOIN
		S2_HR.HR_EMP_ADDR_PERSONAL		ADP
	ON	JOB.EMPLOYEE_ID					= ADP.EMPLOYEE_ID
LEFT OUTER JOIN
		S2_HR.HR_EMP_STATUS				EST
	ON	JOB.EMP_STATUS					= EST.EMP_STATUS
LEFT OUTER JOIN
		S2_HR.HR_EMP_TYPE				ETY
	ON	EPL.EMP_TYPE_CD					= ETY.EMP_TYPE
LEFT OUTER JOIN
		S2_HR.HR_EMP_CLASS				ECL
	ON	JOB.EMP_CLASS_CD				= ECL.EMP_CLASS_CD
LEFT OUTER JOIN
		S2_HR.HR_EMP_EVENT_REASON		EVR
	ON	JOB.EVENT_REASON_CD				= EVR.EVENT_REASON_CD
LEFT OUTER JOIN
		S2_REF.REF_ORG_DPT				DPT
 	ON	JOB.DEPT_CD						= DPT.DPT_ID
LEFT OUTER JOIN
		S2_REF.REF_ORG_BU				BU
 	ON	JOB.BU_CD						= BU.BU_ID
LEFT OUTER JOIN
		S2_REF.REF_ORG_CMPY				CMPY
	ON	JOB.CMPY_CD						= CMPY.CMPY_ID
where   JOB.ACTIVE = '1'
GROUP	by
		ADP.COUNTRY_ISO3166_2_CHAR3
,		JOB.CMPY_CD
,		CMPY.CMPY_NAME
,		JOB.BU_CD
,		BU.BU_NAME
,		JOB.DEPT_CD
,		DPT.DPT_NAME
,		EPL.EMPLOYEE_ID
,		JOB.EMP_STATUS
,		EST.STATUS_DESCRIPTION
,		JOB.EVENT_CD
,		JOB.EVENT_REASON_CD
,		EVR.EVENT_REASON_DESC
,		EPL.EMP_TYPE_CD
,		ETY.EMP_TYPE_DESC
,		JOB.EMP_CLASS_CD
,		ECL.EMP_CLASS_DESC
,		JOB.JOB_CODE
,		JOB.JOB_CODE_TITLE
,		JOB.JOB_GRADE
,		JOB.JOB_LEVEL
,		EPL.ACTIVE
,		JOB.DT_VALID_FROM
,		JOB.DT_VALID_TO
,		TRUNC((NVL(EPL.LAST_DATE_WORKED,CURRENT_DATE)
	-	EPL.START_DATE) / 30 ,0)
order   by
        1,2,4,6,8
;